M48
; DRILL file {KiCad (6.0.11)} date Mon Jan 30 02:30:40 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-30T02:30:40-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1339
%
G90
G05
T1
X3.8031Y2.825
X4.0Y3.0219
X4.0Y2.6281
T2
X3.45Y3.3
X3.45Y0.2
T3
X0.9Y3.24
X1.3Y3.24
T0
M30
